# Generated by Django 3.2.8 on 2021-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.CharField(max_length=255)),
            ],
        ),
    ]
